apiVersion: v1
kind: Service
metadata:
  name: incredy-nodeport-service
spec:
  selector:
    app: incredy
  ports:
    - protocol: TCP
      port: 8081 # This is the port in the cluster (inside Kubernetes)
      targetPort: 8081  # This is the port of the application
      nodePort: 32081 # Port to join the application from outside (must be between 30000 and 32767)
  type: NodePort