apiVersion: apps/v1
kind: Deployment
metadata:
  name: incredy-deployment
  labels:
    app: incredy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incredy
  template:
    metadata:
      labels:
        app: incredy
    spec:
      containers:
      - name: incredy
        image: docker.io/library/docker-with-spring-profile:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
